### ISSUE TITLE
documentation to show ESM import  and usage

### ISSUE THREAD

**Issue by henriquez** [markedjs/marked#1692]
**Describe the bug**
I'm using rollup to bundle dependencies (for a Svelte framework web app) but having trouble importing and using markedjs.  It appears the library was recently ported to ESM modules, but I don't see any documentation on how to use as such.  The standard syntax to import ES6 modules give me errors:

`import { marked }  from 'marked.esm';`
returns
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
marked.esm (imported by src/parser/parser.js)
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
marked.esm (guessing 'marked')

and 

`import { marked }  from 'marked';`
returns 
bundles src/main.js → public/build/bundle.js...
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/marked/lib/marked.js
14:   typeof define === 'function' && define.amd ? define(factory) :
15:   (global = global || self, global.marked = factory());
16: }(this, (function () { 'use strict';
      ^
17: 
18:   function _defineProperties(target, props) {
[!] Error: 'marked' is not exported by node_modules/marked/lib/marked.js, imported by src/parser/parser.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/parser/parser.js (11:9)

**To Reproduce**
npm install marked

in a Svelte js file that's bundled by rollup:
import { marked }  from 'marked';   // or similar variations

**Expected behavior**
no import errors

**Comment by KilianKilmister** [comment]
marked.esm is using a default export instead of a named export. so the proper syntax would be:

```js
import marked from 'marked' // note that this is a definition, so you can give it any name you want
```

But i think you are raising an important point: Why was a default export chosen over a named export? It removes many of the advantages of using esm. As the result is still just some convoluted mess of properties.

It would be much more userfriendly with well organized named exports as they work excellently with TS-language-features.

I'll file a seperate issue about that in a bit

**Comment by henriquez** [comment]
I tried that syntax as well, but errors with "'default' is not exported by node_modules/marked/lib/marked.js" detail below:

`bundles src/main.js → public/build/bundle.js...
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/marked/lib/marked.js
14:   typeof define === 'function' && define.amd ? define(factory) :
15:   (global = global || self, global.marked = factory());
16: }(this, (function () { 'use strict';
      ^
17: 
18:   function _defineProperties(target, props) {
[!] Error: 'default' is not exported by node_modules/marked/lib/marked.js, imported by src/parser/parser.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/parser/parser.js (10:7)
 8: 
 9: /*************** Imports *****************/
10: import marked from 'marked';'`

Looking at lib/marked.esm.js#L2356 it exports default, but if I try
`import marked from 'marked_esm';`
 that errors with
`(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
marked_esm (imported by src/parser/parser.js)
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
marked_esm (guessing 'marked')
`
and in my js I get 

Uncaught ReferenceError: marked is not defined

with
`marked.lexer('# heading');`

**Comment by UziTech** [comment]
have you tried `import marked from marked/lib/marked.esm.js`?

**Comment by henriquez** [comment]
Yes, that errors with "marked is not defined".  Short term I'll just add
the library from an html script tag, but would be nice if modules worked.

**Comment by UziTech** [comment]
I don't usually use esm since it is still experimental in node. If anyone wants to create a PR I would be happy to review it.

**Comment by evanplaice** [comment]
Here's the usage

```javascript
import Marked from '../node_modules/marked/lib/marked.esm.js'

Marked(rawMarkdown)
```

I'm using it in the `<wc-markdown>` web component

**Comment by KilianKilmister** [comment]
cjs-require/esm-import can be automatically handled by specifying an `"exports"` field in the package.json.
This way node will load the appropriate files without the user having to worry about in-module paths.


## Short explanation

```js
{
  "exports": {
    [exportPath]: {
      "import": "path/to/file.mjs",
      "require": "path/to/file.cjs"
    }
  }
}
```


### So for marked it would be:

```jsonc
{
  "exports": {
    ".": {
      "import": "lib/marked.esm.js",
      "require": "lib/marked.js"
    }
  }
}
```

I'll file a PR for that shortly

**Comment by hatboysam** [comment]
Ran into this issue today building my site with Vue 2 and the Vue CLI.  Been developing locally for months and using `marked` heavily, in my Vue component I had:

```
import marked from "marked";
```

When I deployed to production this exploded, marked was not available.  Had to replace it with:
```
const marked = require("marked");
```

Took me a while to figure this out.

**Comment by UziTech** [comment]
I just tried it and it works to import in node v14

```js
// index.js
import marked from "marked";
console.log(marked("# test"));
// <h1 id="test">test</h1>
```

**Comment by jamesb93** [comment]
I think this is related but in SvelteKit next.89 I now get errors when importing marked that I didn't get before and is a complex problem in consideration of SSR.

```
    import marked from 'marked';
```

results in:

```
[vite] Error when evaluating SSR module /node_modules/.pnpm/marked@2.0.3/node_modules/marked/src/marked.js:
ReferenceError: require is not defined
    at /node_modules/.pnpm/marked@2.0.3/node_modules/marked/src/marked.js:1:15
    at instantiateModule (/Users/james/dev/webdev/phd-kit/node_modules/.pnpm/vite@2.2.3/node_modules/vite/dist/node/chunks/dep-994e0558.js:69063:166)
Line must be greater than or equal to 1, got -1
TypeError: Line must be greater than or equal to 1, got -1
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/Users/james/dev/webdev/phd-kit/node_modules/.pnpm/vite@2.2.3/node_modules/vite/dist/node/chunks/dep-994e0558.js:67940:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/Users/james/dev/webdev/phd-kit/node_modules/.pnpm/vite@2.2.3/node_modules/vite/dist/node/chunks/dep-994e0558.js:68009:22)
    at /Users/james/dev/webdev/phd-kit/node_modules/.pnpm/vite@2.2.3/node_modules/vite/dist/node/chunks/dep-994e0558.js:68969:34
    at String.replace (<anonymous>)
    at /Users/james/dev/webdev/phd-kit/node_modules/.pnpm/vite@2.2.3/node_modules/vite/dist/node/chunks/dep-994e0558.js:68959:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/Users/james/dev/webdev/phd-kit/node_modules/.pnpm/vite@2.2.3/node_modules/vite/dist/node/chunks/dep-994e0558.js:68958:10)
    at Object.ssrFixStacktrace (/Users/james/dev/webdev/phd-kit/node_modules/.pnpm/vite@2.2.3/node_modules/vite/dist/node/chunks/dep-994e0558.js:69215:27)
    at Object.handle_error (file:///Users/james/dev/webdev/phd-kit/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.89_svelte@3.37.0+vite@2.2.3/node_modules/@sveltejs/kit/dist/chunks/index.js:3317:19)
    at respond$1 (file:///Users/james/dev/webdev/phd-kit/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.89_svelte@3.37.0+vite@2.2.3/node_modules/@sveltejs/kit/dist/ssr.js:956:11)
```

This problem does not happen if I navigate to the page which uses marked from another page. If I go there directly the problem is 100% reproducible.

**Comment by UziTech** [comment]
This wsa fixed in #2227

**Comment by stolinski** [comment]
I'm still seeing some weirdness here on the latest. (4.0.4)
<img width="995" alt="Screen Shot 2021-11-21 at 10 52 32 AM" src="https://user-images.githubusercontent.com/669383/142773313-0b1d7441-4f28-41dc-a2e8-252b36b31ca4.png">
 
Code compile fine, works in browser, VSCode shows this.

**Comment by UziTech** [comment]
@stolinski it doesn't look like you have @types/marked installed in that repo.

**Comment by GhislainMitahi** [comment]
Hi you all, i need to import and marked in my react project, so when i compile this is the message it gives me, some one can help please :

export 'default' (imported as 'Marked') was not found in 'marked' (possible exports: Lexer, Parser, Renderer, Slugger, TextRenderer, Tokenizer, defaults, getDefaults, lexer, marked, options, parse, parseInline, parser, setOptions, use, walkTokens)

**Comment by UziTech** [comment]
Use `import { marked } from 'marked'` like the error says marked doesn't have a default export.
