### ISSUE TITLE
6.0 broke the build

### ISSUE THREAD

**Issue by blackfalcon** [markedjs/marked#2913]
**Marked version:**

6.0.0

**Describe the bug**
We've been using Marked as a CDN resource for multiple demo pages we create. With the 6.0 release, these pages stopped working. 

I am not sure if there is a bug or if there is a new config consideration that I am not seeing in the docs. 

```
Uncaught (in promise) ReferenceError: marked is not defined
```

**To Reproduce**
You can see how we use Marked in this example. 
https://github.com/AlaskaAirlines/auro-alert/blob/9188f2b4cbf0f319e3ce59bfa326611ecc3c0b5e/demo/index.html#L19-L29

Again, setting the version to 5.1.0, this code renders the markdown as expected. 

```js
    <script type="module">
      import 'https://unpkg.com/marked@5.1.0/marked.min.js';
      import 'https://unpkg.com/prismjs@latest/prism.js';
      fetch('/demo/demo.md')
        .then((response) => response.text())
        .then((text) => {
          const rawHtml = marked.parse(text);
          document.querySelector('main').innerHTML = rawHtml;
          Prism.highlightAll();
        });
    </script>
```

**Expected behavior**

The markdown renders as HTML as expected.

**Comment by UziTech** [comment]
Looks like tsup doesn't create the umd build correctly

**Comment by blackfalcon** [comment]
Finding broken builds across the internets... 

https://github.com/semantic-release/semantic-release/actions/runs/5722193126/job/15504881612#step:6:48

**Comment by alkun-org** [comment]
I just realized same issue on my webpage, using cdn, any ETA on this fix?

**Comment by fu-sen** [comment]
[My project](https://github.com/fu-sen/strapdown) is also broken with 6.0.0. Everything was fine until 5.1.2.
Try #2916, this works.

**Comment by UziTech** [comment]
This should be fixed in v7.0.1

**Comment by blackfalcon** [comment]
This issue is still NOT resolved. 

<img width="1118" alt="Screen Shot 2023-08-08 at 12 20 19 PM" src="https://github.com/markedjs/marked/assets/181089/bc190e87-fb87-45a4-b3a4-6912711695d4">

**Comment by blackfalcon** [comment]
Changing our configuration to the following also addresses our issues 

```
    <script>
      fetch('/demo/demo.md')
        .then((response) => response.text())
        .then((text) => {
          const rawHtml = marked.parse(text);
          document.querySelector('main').innerHTML = rawHtml;
          Prism.highlightAll();
        });
    </script>
    <script type="module" src="../index.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/prismjs@latest/prism.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/marked@latest/marked.min.js"></script>
```
