### ISSUE TITLE
Bug with asterisks (if this is the current version of GFM on GitHub)

### ISSUE THREAD

**Issue by alanhogan** [markedjs/marked#520]
Sorry if this is filed incorrectly, but strings like this are not formatted correctly:

`Test *italic here **bold italic here** and italic still* end`

See also http://ajh.us/babelmark2-asterisks-bold-in-italic-test

**Comment by CoDEmanX** [comment]
It also fails at a very simple:

    text text *five \*six* text

Result should look like:
> text text *five * six* text

http://johnmacfarlane.net/babelmark2/?normalize=1&text=text+text+*five+\*+six*

**Comment by sunil-ideas2it** [comment]
Anyone got fix for this .

**Comment by joshbruce** [comment]
Closing as covered by spec-compliance. See also #1106 and #1216

**Comment by Feder1co5oave** [comment]
This still [fails](https://marked.js.org/demo/?outputType=html&text=text%20text%20*five%20%5C*six*%20text&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tables%22%3A%20true%2C%0A%20%22xhtml%22%3A%20false%0A%7D):
```markdown
text text *five \*six* text
```

```html
<p>text text <em>five \</em>six* text</p>

```

**Comment by rtxa** [comment]
Hi, I've fixed this by not matching the backslash character in the regex for the 5th group, this needs to be tested to ensure there aren't side effects. Check this [Regex demo](https://regex101.com/r/onVNcp/1)

Original code:
https://github.com/markedjs/marked/blob/c99e69b406f6c22bc27e29e4a85bf66e598071d2/lib/marked.js#L564

Fix:
```js
em: /^_([^\s_])_(?!_)|^\*([^\s*"<\[])\*(?!\*)|^_([^\s][\s\S]*?[^\s_])_(?!_|[^\spunctuation])|^_([^\s_][\s\S]*?[^\s])_(?!_|[^\spunctuation])|^\*([^\s"<\[][\s\S]*?[^\s*][^\\])\*(?!\*)|^\*([^\s"<\[][\s\S]*?[^\s*][^\\])\*(?!\*)/,
```

**Comment by UziTech** [comment]
@rtxa you should create a PR so it can be tested by our test suite

**Comment by 01010101lzy** [comment]
Sorry to dig up this issue, but is there any updates on this issue? Seems it's still present as of v1.2.2.

**Comment by UziTech** [comment]
There are still some issues with em but it looks like the original bug is fixed:

```
Test *italic here **bold italic here** and italic still* end

<p>Test <em>italic here <strong>bold italic here</strong> and italic still</em> end</p>
```

[demo](https://marked.js.org/demo/?text=Test%20*italic%20here%20**bold%20italic%20here**%20and%20italic%20still*%20end&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)

@01010101lzy if you have other markdown that is not working you can create a different issue.

**Comment by 01010101lzy** [comment]
> There are still some issues with em but it looks like the original bug is fixed:
> 
> ```
> Test *italic here **bold italic here** and italic still* end
> 
> <p>Test <em>italic here <strong>bold italic here</strong> and italic still</em> end</p>
> ```
> 
> [demo](https://marked.js.org/demo/?text=Test%20*italic%20here%20**bold%20italic%20here**%20and%20italic%20still*%20end&options=%7B%0A%20%22baseUrl%22%3A%20null%2C%0A%20%22breaks%22%3A%20false%2C%0A%20%22gfm%22%3A%20true%2C%0A%20%22headerIds%22%3A%20true%2C%0A%20%22headerPrefix%22%3A%20%22%22%2C%0A%20%22highlight%22%3A%20null%2C%0A%20%22langPrefix%22%3A%20%22language-%22%2C%0A%20%22mangle%22%3A%20true%2C%0A%20%22pedantic%22%3A%20false%2C%0A%20%22sanitize%22%3A%20false%2C%0A%20%22sanitizer%22%3A%20null%2C%0A%20%22silent%22%3A%20false%2C%0A%20%22smartLists%22%3A%20false%2C%0A%20%22smartypants%22%3A%20false%2C%0A%20%22tokenizer%22%3A%20null%2C%0A%20%22walkTokens%22%3A%20null%2C%0A%20%22xhtml%22%3A%20false%0A%7D&version=master)
> 
> @01010101lzy if you have other markdown that is not working you can create a different issue.

The problem mentioned in the first reply of this issue (asterisks are not properly escaped) is still lying around unfortunately...

https://marked.js.org/demo/?text=*test%5C*%20123*&options=%7B%20%22baseUrl%22%3A%20null%2C%20%22breaks%22%3A%20false%2C%20%22gfm%22%3A%20true%2C%20%22headerIds%22%3A%20true%2C%20%22headerPrefix%22%3A%20%22%22%2C%20%22highlight%22%3A%20null%2C%20%22langPrefix%22%3A%20%22language-%22%2C%20%22mangle%22%3A%20true%2C%20%22pedantic%22%3A%20false%2C%20%22sanitize%22%3A%20false%2C%20%22sanitizer%22%3A%20null%2C%20%22silent%22%3A%20false%2C%20%22smartLists%22%3A%20false%2C%20%22smartypants%22%3A%20false%2C%20%22tokenizer%22%3A%20null%2C%20%22walkTokens%22%3A%20null%2C%20%22xhtml%22%3A%20false%7D&version=master

**Comment by UziTech** [comment]
@01010101lzy yes that is still an issue. If you want to you can create a different issue to track that bug. PRs are also welcome. 😁
